disabled_rules: # rule identifiers to exclude from running
#  - trailing_whitespace
#
whitelist_rules:

opt_in_rules:
  - mark
  - private_outlet
  - vertical_whitespace
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - file_name
  - first_where
  - modifier_order
  - prohibited_interface_builder
  - toggle_bool
  - unused_private_declaration
  - fallthrough
  - identical_operands
  - joined_default_parameter
  - unavailable_function
  - overriden_super_call

#  - closure_spacing
#  - colon
#  - empty_enum_arguments
#  - fatal_error_message
#  - force_cast
#  - force_try
#  - force_unwrapping
#  - implicitly_unwrapped_optional
#  - legacy_cggeometry_functions
#  - legacy_constant
#  - legacy_constructor
#  - legacy_nsgeometry_functions
#  - operator_usage_whitespace
#  - redundant_string_enum_value
#  - redundant_void_return
#  - return_arrow_whitespace
#  - trailing_newline
#  - type_name
#  - unused_closure_parameter
#  - unused_optional_binding
#  - vertical_whitespace
#  - void_return
#  - custom_rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - fastlane

colon:
  apply_to_dictionaries: false

indentation: 4

line_length:
warning: 142
error: 142

mark:
  severity: error

vertical_whitespace:
  severity: error

type_name:
  max_length: 60

variable_name:
  min_length: 3
  excluded:
    - id
    - y
    - x
