excluded:
  - Pods
  - fastlane
  - ios-base-architectureTests
  - ios-base-architectureUITests

analyzer_rules:
  - unused_declaration
  - unused_import
  - unused_private_declaration

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_enum_arguments
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
#  - file_header
  - file_name
  - first_where
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_string_enum_value
  - redundant_optional_initialization
  - redundant_type_annotation
  - redundant_void_return
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_optional_binding
  - unused_private_declaration
  - vertical_whitespace
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - xct_specific_matcher
  - yoda_condition

identifier_name:
  min_length: 2
  excluded:
    - id
    - y
    - x

line_length:
  warning: 140
  error: 180

mark:
  severity: error

vertical_whitespace:
  severity: error
