# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-base-architecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-base-architecture
  pod 'SwiftLint'

  target 'ios-base-architectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-base-architectureUITests' do
    # Pods for testing
  end

end
