 platform :ios, '13.2'

target 'GHProjects' do
  use_frameworks!

  pod 'SwiftLint'

  target 'GHProjectsTests' do
    inherit! :search_paths

  end

  target 'GHProjectsUITests' do
    pod 'KIF'
    pod 'KIF/IdentifierTests'
  end

end
